spring:
  application:
    name: prescription-service
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    database: H2
    properties:
      hibernate:
        check_nullability: true    #hibernate check nullability before execute query
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    url: ${datasource.url:jdbc:h2:mem:prescriptiondb}   #TODO: fetch value from HashiCorp Vault
    username: ${datasource.username:sa}                 #TODO: fetch value from HashiCorp Vault
    password: ${datasource.password:1}                  #TODO: fetch value from HashiCorp Vault
  zipkin:
    base-url: http://localhost:9411

#logging:
#  level:
#    root: DEBUG

#ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: '*'

#DOCUMENTATION
springdoc:
  api-docs:
    enabled: true
    path: /prescription-service/v3/api-docs
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /prescription-service/swagger-ui.html
  paths-to-match: /api/**

#EUREKA
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}