spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: medication-service
          uri: lb://medication-service
          predicates:
            - Path=/api/v1/medication/**    # bu ?ekilde gelen iste?i medicationService'e ilet demek
        - id: prescription-service
          uri: lb://prescription-service
          predicates:
            - Path=/api/v1/prescription/**
      discovery:
        locator:
          enabled: true

server:
  port: 8889

#EUREKA
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

#ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info